apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 2   # run 2 pods for availability
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: my-dockerhub-username/my-react-app:latest  # will be replaced by Jenkins
        ports:
        - containerPort: 80
